### ISSUE TITLE
Getting a lot of errors after/during usage of GNOME ScreenCast portal

### ISSUE THREAD

**Issue by benzea** [PipeWire/pipewire#111]
My log is being spammed with the following message:

```
Dec 08 13:24:51 ben-x1 pipewire[17474]: [E][connection.c:513 pw_protocol_native_connection_flush()] could not sendmsg: Resource temporarily unavailable
```

To be honest, I am currently not sure how I triggered this situation. A quick try to reproduce it with the example python code did not result in any issue.

**Comment by benzea** [comment]
I don't seem to be getting these with a daemon compiled from master rather than the F29 version.

I guess most likely the issue has been fixed in some way.

**Comment by benzea** [comment]
Actually, it does seem to happen with (a reasonably new) master. The error seems to be related to doing a suspend/resume cycle though.

I just got 8 of these errors for one suspend/resume cycle.

**Comment by gkiagia** [comment]
I have been seeing this randomly as well. This seems to be related to how big messages are and it is easier to reproduce when the graph has at least 200 objects (nodes, ports, links, all included)

This is coming from `sendmsg()` in `pw_protocol_native_connection_flush()`, which is called with `MSG_DONTWAIT` and naturally, sometimes it returns `-EAGAIN`, probably because the buffers are full. This return value is not handled, though. This effectively causes some packet loss which makes clients misbehave (they succeed in doing some calls, but others just hang or don't have any effect)
