### ISSUE TITLE
portal screen-cast permission handling is broken

### ISSUE THREAD

**Issue by michaelolbrich** [PipeWire/pipewire#158]
Since 83bc033837f7 screen cast with xdg-desktop-portal 1.4.x no longer works.

The problem is, that xdg-desktop-portal only sets the correct permissions for the ClientNode factory but not for its parent (the corresponding module).

Since 83bc033837f7 all parent are checked as well. As a result access to the ClientNode factory is denied.

I'm not sure where this should be fixed, but expecting the clients to iterate all parents to set the correct permissions seems wrong to me.

**Comment by wtay** [comment]
> Since [83bc033](https://github.com/PipeWire/pipewire/commit/83bc033837f7525d898f1de91119f669f9bf97f5) all parent are checked as well. As a result access to the ClientNode factory is denied.
> 
> I'm not sure where this should be fixed, but expecting the clients to iterate all parents to set the correct permissions seems wrong to me.

I can't see how else this could work.. The problem is that if we don't require permissions on the complete hierarchy, it might be possible to see that an object-id exists (because it's a parent of some object you can see) but you can't read it, that sounds wrong too...

Or if it is like directories, you can see there is a parent but not what's in it? It would then be that you can see all object as globals but not bind to them to get more details? that sounds like revealing too much information..

**Comment by michaelolbrich** [comment]
Maybe fix it at the other end in pw_core_proxy_permissions() or at least make it easier. Some way to say: 'I want these permissions for this node and all other permissions to make this possible'. Basically add the parent node permissions implicitly.

**Comment by wtay** [comment]
It harder and more expensive, because then I either:

1) need to set (READ) permissions automatically on the parents (when not set before) when setting a permission (READ) on a child. I also need to remember this and remove the parent permission when the child permission is removed again.
2) Do a deep check every time for an object by checking if one of the children or subchildren is visible.

I think maybe a new internal counter could work, If a child is made readable, increment parent counters, when a child is made invisible or removed, decrement counter. When checking for readability either the object needs explicit read permissions or a counter>0.

**Comment by wtay** [comment]
Parent permissions checks (and the parent) are removed. Security on related objects needs to be handled manually now.
