### ISSUE TITLE
Will we be able to use A2DP and HSP/HFP simultaneously in the future?

### ISSUE THREAD

**Issue by Superdanby** [PipeWire/pipewire#45]
Because HSP/HFP is suffering from low quality issues, it'd be awesome to have A2DP used for output and HSP/HFP used for input at the same time, which is currently not available with Pulseaudio.

**Comment by hadess** [comment]
You can't use both at the same time, the devices just don't support it. What phones, tablets and PulseAudio do (although somewhat clumsily, due to various bugs in devices) is automatically switch profiles on the fly, depending on the requesting application. Eg. PulseAudio would automatically switch from the A2DP music stream to an HSP/HFP one when your video chat app opens a call.

**Comment by wtay** [comment]
Closing this as WONTFIX or even like CANTFIX
