### ISSUE TITLE
Some ideas, from a wandering mind.

### ISSUE THREAD

**Issue by ranomier** [PipeWire/pipewire#69]
I'm no expert programmer so maybe my thoughts do not have any weight, but maybe they contribute, so i want to share them here.

1. I think the basis of every audio server should basicly be like a basic jack. So every software can register inputs and outputs. But a little different to jack:
1.1. It should handle all _hardware_ inputs and outputs by default like pulse. I don't know how realtime is implented in the kernel, but if only one soundcard can be handled in realtime mode, they should be a possibilty to set one (maybe more) soundcard in realtime mode.
1.2. Every output should get the posibilty to have a volume control, built in the core. But it should be bypassable.
1.3. Groups: If we have 5.1 souround sound, a audio output could create a group with 6 channels, so the audio manager knows they should stay together. Maybe the groups could hold accesable data with them, so a audio manager knows what do with them, but im not sure if that could complicate things.

2. Let handle a _second software_ the audio routing (a audio routing manager), this software does nothing but to do that one thing. And they could be several of them. One that acts like PulseAudio and even a gui could look like pavucontrol.
2.1. As suggested in point 1.2. The _audio routing manager_ should be able to control the bypass.

3. The third thing would be a framework to easily add interfaces. For example a interface for pulseaudio or jack or alsa, etc.

Sorry if i made a mistake, english is not my native language, but i try hard :)

What do you guys think about these ideas?

**Comment by ranomier** [comment]
Ah and i also think it could be helpful that every software that registers inputs and outputs should be identifiable, by several things.
- a name that they self choose, like Jack
- the PID
- the path to the binary.
- maybe more

:)

**Comment by wtay** [comment]
This is pretty much the current state of PipeWire (regarding audio, video is pretty much the same).

1 I agree, the basic idea is a jack-like graph of devices and clients each providing nodes and ports that
can be linked in arbitrary ways.

1.1 All alsa devices are visible and appear/disappear when plugged. This also applies to bluetooth devices that are connected or even cameras. The audio devices each form a session and have an adapter object (the DSP) associated with them. Jack clients only get to see the audio DSP ports for now.

1.2 there is no software volume control implemented directly into the device or in the DSP frontend of the device. (except for the hardware volume control). It could be fairly trivial to add volume to the DSP. But yet another volume together with the hardware volume seems unnecessary...

1.3 a DSP frontend groups channels into logical groups, the port also have properties to tag the channel layout.

2. The connection and session management is done with a module. It runs inside the server but could be disabled or simply be replaced with another implementation. It could be possible to implement the routing in a separate process but that would have more overhead and It probably needs some more thinking.

2.1 

3. Regarding supporting legacy apps and apis It seems to be more flexible to do a reimplementation of the client side libraries. For alsa there is a pcm plugin, for JACK there is a libjack.so implementation and for pulseaudio I plan to make a new libpulse.so library. It's a bit more complicated to implement the pulse library because it's so big but certainly easier than to reimplement the complete communication protocol. 

Something else:

There are basically 2 API's to interface with PipeWire:

1) use the stream API (pw_stream). This one only does 1 direction (input/output) but can do conversion
of the format, allows custom latency and allows exclusive access or shared. The session manager links
the stream client to the DSP or directly to the device node depending on requirements. This is the API that multimedia apps and the alsa pcm plugin would use. It's similar to the pulseaudio API or AudioQueue from core audio.

2) the export API. You basically implement a node with ports and export that into a Remote PipeWire instance. It's comparable to the JACK client API or LADSPA/LV2. This is more complicated but gives you
more control over all aspect of the processing (buffer size, formats, ...). The stream API is implemented
on top of this.

**Comment by ranomier** [comment]
Thanks for the answer :). I will have to read it several times, so it will take some time. Just that you know that still on it. :3

**Comment by ranomier** [comment]
What is "DSP frontend" and "DSP ports"?

> 1 I agree, the basic idea is a jack-like graph of devices and clients each providing nodes and ports that
can be linked in arbitrary ways.

Awesome <3

> 1.1 All alsa devices are visible and appear/disappear when plugged. This also applies to bluetooth devices that are connected or even cameras. The audio devices each form a session and have an adapter object (the DSP) associated with them. Jack clients only get to see the audio DSP ports for now.

What i think is important, to move forward, is that every software should be connectable to every other software or hardware in arbitrary ways. So Jack clients should be able connect to Pulseaudio or every other API. So you can use it like Jack with every software.
e.G.
Firefox is connected via Pulseaudio and has to open io ports. I wan't to connect one of them to Audacity that uses JACK. Maybe i throw some effects in between.
The other is connected to my headphones output and my bluetooth headphones, but not to the speakers. Just like Jack, but it isn't important which API a software uses.

> 1.2 there is no software volume control implemented directly into the device or in the DSP frontend of the device. (except for the hardware volume control). It could be fairly trivial to add volume to the DSP. But yet another volume together with the hardware volume seems unnecessary...

What i meant was that every output, even software that registered an io port, but after thinking i think inputs should get that, too. If that's not the case, we would need a third party mixer that is only for volume.

> 1.3 a DSP frontend groups channels into logical groups, the port also have properties to tag the channel layout.
Sounds like what i meant, but i'm not sure.

> Regarding supporting legacy apps and apis It seems to be more flexible to do a reimplementation of the client side libraries. For alsa there is a pcm plugin, for JACK there is a libjack.so implementation and for pulseaudio I plan to make a new libpulse.so library. It's a bit more complicated to implement the pulse library because it's so big but certainly easier than to reimplement the complete communication protocol.

sounds right to me. :3 


The last bit with API's was too technical. I try my best :)

Thanks for the great Answer.

**Comment by ranomier** [comment]
Thanks for your answers. PipeWire sounds awesome. :)

**Comment by ranomier** [comment]
By the way maybe this helps you:

https://gavv.github.io/blog/pulseaudio-under-the-hood/

You could close the ticket or we transfer some of the information's from here into the wiki.

**Comment by ranomier** [comment]
mmh i think i close it then :)
